In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','resume_score','package']) #created the same dataser

In [3]:
df

cgpa  resume_score  package
0     8             8        4
1     7             9        5
2     6            10        6
3     5            12        7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

D:\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
#keras randomly inilitazie the weights and bias
model.get_weights()

[array([[-0.6837161 , -0.05656195],
        [-0.29645407, -1.1080487 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0924848],
        [-1.2566706]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
#to make weights and bias similar to out model
new_weights = [np.array([[0.1 , 0.1],
        [0.17,0.1 ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[ 0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [16]:
model.set_weights(new_weights)

In [17]:
model.get_weights()

[array([[0.1 , 0.1 ],
        [0.17, 0.1 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [19]:
model.fit(df.iloc[:,0:-1].values,df['package'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 22.3135
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 32.9774
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 27.2441
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32.1713
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.8150
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29.0486
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 28.6289
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 21.3956
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.2236
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.1014
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 29.0291
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22.4908
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 27.0930
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20.0505
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 19.4273
Epoch 16/75
4/4 ━━━

In [20]:
model.get_weights()

[array([[0.36759648, 0.3697619 ],
        [0.43021303, 0.36228225]], dtype=float32),
 array([0.2665682 , 0.26870257], dtype=float32),
 array([[0.35559842],
        [0.36933428]], dtype=float32),
 array([0.20210068], dtype=float32)]